Repository lightspeed/flame, pull requests merged in 2019-10, with the labels that each got.

#9 Move flags and icons SVGs to their respective namespace
  packages/flame/CHANGELOG.md
  packages/flame/scripts/copy-files.js
  packages/flame/scripts/generate-flags.js
  packages/flame/scripts/generate-icons.js
  packages/flame/src/Icon/examples/story.tsx
Labels: pkg: flame

#15 Add <Alert /> `icon` prop
  packages/flame/CHANGELOG.md
  packages/flame/src/Alert/Alert.test.tsx
  packages/flame/src/Alert/Alert.tsx
  packages/flame/src/Alert/README.md
  packages/flame/src/Alert/__snapshots__/Alert.test.tsx.snap
  packages/flame/src/Alert/index.tsx
  packages/flame/src/Alert/story.tsx
Labels: design approved ⚡️

#26 Better mobile responsiveness for Checkbox/Radio
  packages/flame/CHANGELOG.md
  packages/flame/src/Checkbox/Checkbox.tsx
  packages/flame/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/flame/src/Checkbox/story.tsx
  packages/flame/src/Radio/Radio.tsx
  packages/flame/src/Radio/__snapshots__/Radio.test.tsx.snap
  packages/flame/src/Radio/story.tsx
  stories/helpers/percy.ts
Labels: design approved ⚡️

#2 Rework Group and Inputs
  jest.config.js
  packages/flame/CHANGELOG.md
  packages/flame/src/Button/BaseButton.tsx
  packages/flame/src/Button/story.tsx
  packages/flame/src/Checkbox/Checkbox.test.tsx
  packages/flame/src/Checkbox/Checkbox.tsx
  packages/flame/src/Checkbox/README.md
  packages/flame/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/flame/src/Checkbox/index.tsx
  packages/flame/src/Checkbox/story.tsx
  packages/flame/src/Core/index.tsx
  packages/flame/src/Dialog/Dialog.tsx
  packages/flame/src/Dialog/story.tsx
  packages/flame/src/Flag/examples/story.tsx
  packages/flame/src/FormField/FormField.test.tsx
  packages/flame/src/FormField/FormField.tsx
  packages/flame/src/FormField/README.md
  packages/flame/src/FormField/index.tsx
  packages/flame/src/FormField/story.tsx
  packages/flame/src/Group/Group.test.tsx
  packages/flame/src/Group/Group.tsx
  packages/flame/src/Group/README.md
  packages/flame/src/Group/__snapshots__/Group.test.tsx.snap
  packages/flame/src/Group/index.tsx
  packages/flame/src/Group/story.tsx
  packages/flame/src/Input/Input.test.tsx
  packages/flame/src/Input/Input.tsx
  packages/flame/src/Input/README.md
  packages/flame/src/Input/__snapshots__/Input.test.tsx.snap
  packages/flame/src/Input/index.tsx
  packages/flame/src/Input/story.tsx
  packages/flame/src/InputGroup/InputGroup.tsx
  packages/flame/src/InputGroup/README.md
  packages/flame/src/InputGroup/index.tsx
  packages/flame/src/InputGroup/story.tsx
  packages/flame/src/Radio/README.md
  packages/flame/src/Radio/Radio.test.tsx
  packages/flame/src/Radio/Radio.tsx
  packages/flame/src/Radio/__snapshots__/Radio.test.tsx.snap
  packages/flame/src/Radio/examples/index.tsx
  packages/flame/src/Radio/index.tsx
  packages/flame/src/Radio/story.tsx
  packages/flame/src/Select/Select.tsx
  packages/flame/src/Spinner/story.tsx
  packages/flame/src/Switch/story.tsx
  packages/flame/src/Tab/README.md
  stories/components/SpacedGroup.tsx
Labels: enhancement
